/*
Script generated by Aqua Data Studio 7.0.15 on Dec-05-2008 05:56:05 PM
Database: appform
Schema: <All Schemas>
Objects: TABLE, SEQUENCE
*/
ALTER TABLE `public`.`usr_pat_intrinst`
	DROP CONSTRAINT `fk_usr_ternary_rel` CASCADE ;
ALTER TABLE `public`.`usr_pat_intrinst`
	DROP CONSTRAINT `fk_pat_ternary_rel` CASCADE ;
ALTER TABLE `public`.`usr_pat_intrinst`
	DROP CONSTRAINT `fk_intr_ins_ternary_rel` CASCADE ;
ALTER TABLE `public`.`user_role`
	DROP CONSTRAINT `fk_userrole_user` CASCADE ;
ALTER TABLE `public`.`user_role`
	DROP CONSTRAINT `fk_userrole_role` CASCADE ;
ALTER TABLE `public`.`user_role`
	DROP CONSTRAINT `fk143bf46a289fe600` CASCADE ;
ALTER TABLE `public`.`user_role`
	DROP CONSTRAINT `fk143bf46a1c3f28d3` CASCADE ;
ALTER TABLE `public`.`text`
	DROP CONSTRAINT `fk_text_itemisa_item` CASCADE ;
ALTER TABLE `public`.`text`
	DROP CONSTRAINT `fk27b94df0028e8c` CASCADE ;
ALTER TABLE `public`.`section`
	DROP CONSTRAINT `fk_section_is_formed_interview` CASCADE ;
ALTER TABLE `public`.`section`
	DROP CONSTRAINT `fk756f7ee57bd5537b` CASCADE ;
ALTER TABLE `public`.`rel_prj_appusers`
	DROP CONSTRAINT `fkd0e56e24bc927c7a` CASCADE ;
ALTER TABLE `public`.`rel_prj_appusers`
	DROP CONSTRAINT `fkd0e56e24289fe600` CASCADE ;
ALTER TABLE `public`.`rel_prj_appusers`
	DROP CONSTRAINT `fk_rel_prj__rel_prj_a_project` CASCADE ;
ALTER TABLE `public`.`rel_prj_appusers`
	DROP CONSTRAINT `fk_rel_prj__rel_prj_a_appuser` CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	DROP CONSTRAINT `fk_rel_grp__rel_grp_a_appuser` CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	DROP CONSTRAINT `fk_rel_grp__rel_grp_a_appgroup` CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	DROP CONSTRAINT `fk3e240fd3e9d1abd4` CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	DROP CONSTRAINT `fk3e240fd3289fe600` CASCADE ;
ALTER TABLE `public`.`question`
	DROP CONSTRAINT `fkba823be6e7b3fc5` CASCADE ;
ALTER TABLE `public`.`question`
	DROP CONSTRAINT `fk_question_itemisa2_item` CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	DROP CONSTRAINT `fk_question` CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	DROP CONSTRAINT `fk_answer_item` CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	DROP CONSTRAINT `fk6d9a2ea0b9245433` CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	DROP CONSTRAINT `fk6d9a2ea05c3d6ca1` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fka7c31030e9d1abd4` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fka7c310309fd61a61` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fka7c310307bd5537b` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fka7c31030289fe600` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fk_performa_rel_pat_p_patient` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fk_performa_rel_intrv_intervie` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fk_performa_rel_group` CASCADE ;
ALTER TABLE `public`.`performance`
	DROP CONSTRAINT `fk_performa_rel_appus_appuser` CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	DROP CONSTRAINT `fkd6209a2dcefe49a3` CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	DROP CONSTRAINT `fkd6209a2db9245433` CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	DROP CONSTRAINT `fkd6209a2d9fd61a61` CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	DROP CONSTRAINT `fk_pat_give_rel_ques__question` CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	DROP CONSTRAINT `fk_pat_give_rel_pat_a_patient` CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	DROP CONSTRAINT `fk_pat_give_rel_ans_p_answer` CASCADE ;
ALTER TABLE `public`.`item`
	DROP CONSTRAINT `fk_item_is_formed_section` CASCADE ;
ALTER TABLE `public`.`item`
	DROP CONSTRAINT `fk_item_contains_item` CASCADE ;
ALTER TABLE `public`.`item`
	DROP CONSTRAINT `fk317b13ee6627b7` CASCADE ;
ALTER TABLE `public`.`item`
	DROP CONSTRAINT `fk317b136ead1f80` CASCADE ;
ALTER TABLE `public`.`intrv_group`
	DROP CONSTRAINT `fk_intrvgroup_intrv` CASCADE ;
ALTER TABLE `public`.`intrv_group`
	DROP CONSTRAINT `fk_intrvgroup_group` CASCADE ;
ALTER TABLE `public`.`intrv_group`
	DROP CONSTRAINT `fk84c0ddb3e9d1abd4` CASCADE ;
ALTER TABLE `public`.`intrv_group`
	DROP CONSTRAINT `fk84c0ddb334d3ec6d` CASCADE ;
ALTER TABLE `public`.`intr_instance`
	DROP CONSTRAINT `fk_instance_interview` CASCADE ;
ALTER TABLE `public`.`interview`
	DROP CONSTRAINT `fk_interview_is_formed_project` CASCADE ;
ALTER TABLE `public`.`interview`
	DROP CONSTRAINT `fk_interview_belongs_user` CASCADE ;
ALTER TABLE `public`.`interview`
	DROP CONSTRAINT `fk_cloned_from` CASCADE ;
ALTER TABLE `public`.`interview`
	DROP CONSTRAINT `fk1dfcd181bc927c7a` CASCADE ;
ALTER TABLE `public`.`interview`
	DROP CONSTRAINT `fk1dfcd1819fb025d9` CASCADE ;
ALTER TABLE `public`.`interview`
	DROP CONSTRAINT `fk1dfcd18132dc448d` CASCADE ;
ALTER TABLE `public`.`enumtype`
	DROP CONSTRAINT `fk_enumtype_isoneof2_answer_i` CASCADE ;
ALTER TABLE `public`.`enumtype`
	DROP CONSTRAINT `fk886d93fbda39f0f6` CASCADE ;
ALTER TABLE `public`.`enumitem`
	DROP CONSTRAINT `fk_enumitem_contains_enumtype` CASCADE ;
ALTER TABLE `public`.`enumitem`
	DROP CONSTRAINT `fk849ca7944d54c7fd` CASCADE ;
ALTER TABLE `public`.`appuser`
	DROP CONSTRAINT `fkd0bc6d6cff274c45` CASCADE ;
ALTER TABLE `public`.`appuser`
	DROP CONSTRAINT `fk_hospital_user` CASCADE ;
ALTER TABLE `public`.`appuser`
	DROP CONSTRAINT `fk33f5054cff274c45` CASCADE ;
ALTER TABLE `public`.`appgroup`
	DROP CONSTRAINT `fk_parent_group` CASCADE ;
ALTER TABLE `public`.`appgroup`
	DROP CONSTRAINT `fk_grouptype` CASCADE ;
ALTER TABLE `public`.`appgroup`
	DROP CONSTRAINT `fk460ba8fefa6441bc` CASCADE ;
ALTER TABLE `public`.`appgroup`
	DROP CONSTRAINT `fk460ba8fee20f1477` CASCADE ;
ALTER TABLE `public`.`answertype`
	DROP CONSTRAINT `fkb00210386a4127c5` CASCADE ;
ALTER TABLE `public`.`answertype`
	DROP CONSTRAINT `fk_answerty_isoneof_answer_i` CASCADE ;
ALTER TABLE `public`.`answer`
	DROP CONSTRAINT `fkabca3fbe5c3d6ca1` CASCADE ;
ALTER TABLE `public`.`answer`
	DROP CONSTRAINT `fk_answer_rel_answ__answer_i` CASCADE ;
ALTER TABLE `public`.`answer_item`
	DROP CONSTRAINT `fked6a1af434d3ec6d` CASCADE ;
ALTER TABLE `public`.`answer_item`
	DROP CONSTRAINT `fk_ansitem_intrv` CASCADE ;
DROP SEQUENCE `public`.`applog_logId_seq`;
DROP SEQUENCE `public`.`usr_pat_intrinst_id_upi_seq`;
DROP SEQUENCE `public`.`user_role_iduser_role_seq`;
DROP SEQUENCE `public`.`text_idtext_seq`;
DROP SEQUENCE `public`.`section_idsection_seq`;
DROP SEQUENCE `public`.`role_idrole_seq`;
DROP SEQUENCE `public`.`rel_prj_appusers_idprj_usrs_seq`;
DROP SEQUENCE `public`.`rel_grp_appusr_idgrp_usr_seq`;
DROP SEQUENCE `public`.`question_idquestion_seq`;
DROP SEQUENCE `public`.`question_ansitem_id_seq`;
DROP SEQUENCE `public`.`project_idproject_seq`;
DROP SEQUENCE `public`.`project_idprj_seq`;
DROP SEQUENCE `public`.`performance_idperformance_seq`;
DROP SEQUENCE `public`.`patient_idpatient_seq`;
DROP SEQUENCE `public`.`patient_idpat_seq`;
DROP SEQUENCE `public`.`pat_gives_answer2ques_idp_a_q_seq`;
DROP SEQUENCE `public`.`item_iditem_seq`;
DROP SEQUENCE `public`.`intrv_group_idintrv_group_seq`;
DROP SEQUENCE `public`.`intr_instance_idinstance_seq`;
DROP SEQUENCE `public`.`interview_idinterview_seq`;
DROP SEQUENCE `public`.`hospital_idhosp_seq`;
DROP SEQUENCE `public`.`grouptype_idgrouptype_seq`;
DROP SEQUENCE `public`.`enumitem_idenumitem_seq`;
DROP SEQUENCE `public`.`appuser_iduser_seq`;
DROP SEQUENCE `public`.`appgroup_idgroup_seq`;
DROP SEQUENCE `public`.`answer_item_idansitem_seq`;
DROP SEQUENCE `public`.`answer_idanswer_seq`;
DROP TABLE `public`.`usr_pat_intrinst`;
DROP TABLE `public`.`user_role`;
DROP TABLE `public`.`text`;
DROP TABLE `public`.`section`;
DROP TABLE `public`.`role`;
DROP TABLE `public`.`rel_prj_appusers`;
DROP TABLE `public`.`rel_grp_appusr`;
DROP TABLE `public`.`question`;
DROP TABLE `public`.`question_ansitem`;
DROP TABLE `public`.`project`;
DROP TABLE `public`.`performance`;
DROP TABLE `public`.`patient`;
DROP TABLE `public`.`pat_gives_answer2ques`;
DROP TABLE `public`.`item`;
DROP TABLE `public`.`intrv_group`;
DROP TABLE `public`.`intr_instance`;
DROP TABLE `public`.`interview`;
DROP TABLE `public`.`hospital`;
DROP TABLE `public`.`grouptype`;
DROP TABLE `public`.`enumtype`;
DROP TABLE `public`.`enumitem`;
DROP TABLE `public`.`appuser`;
DROP TABLE `public`.`applog`;
DROP TABLE `public`.`appgroup`;
DROP TABLE `public`.`answertype`;
DROP TABLE `public`.`answer`;
DROP TABLE `public`.`answer_item`;

CREATE TABLE `public`.`answer_item` ( 
	`idansitem`   	int4 NOT NULL DEFAULT nextval('answer_item_idansitem_seq'::regclass),
	`answer_order`	int4 NULL,
	`name`        	varchar(128) NULL,
	`description` 	varchar(128) NULL,
	`codintrv`    	int4 NULL,
	PRIMARY KEY(`idansitem`)
);
CREATE TABLE `public`.`answer` ( 
	`idanswer`    	int4 NOT NULL DEFAULT nextval('answer_idanswer_seq'::regclass),
	`thevalue`    	varchar(512) NULL,
	`answer_order`	int4 NULL,
	`codansitem`  	int4 NOT NULL,
	PRIMARY KEY(`idanswer`)
);
CREATE TABLE `public`.`answertype` ( 
	`idanstype`	int4 NOT NULL,
	`pattern`  	varchar(256) NULL,
	PRIMARY KEY(`idanstype`)
);
CREATE TABLE `public`.`appgroup` ( 
	`idgroup`      	int4 NOT NULL DEFAULT nextval('appgroup_idgroup_seq'::regclass),
	`name`         	varchar(128) NULL,
	`codgroup`     	varchar(128) NULL,
	`tmpl_holder`  	int4 NULL DEFAULT 0,
	`parent`       	int4 NULL,
	`codgroup_type`	int4 NULL,
	PRIMARY KEY(`idgroup`)
);
CREATE TABLE `public`.`applog` ( 
	`logId`    	int4 NOT NULL DEFAULT nextval('"applog_logId_seq"'::regclass),
	`userid`   	int4 NULL,
	`patientid`	int4 NULL,
	`intrvid`  	int4 NULL,
	`logmsg`   	varchar(8192) NULL,
	`sessionid`	varchar(256) NULL,
	`thetime`  	timestamp NULL DEFAULT now(),
	PRIMARY KEY(`logId`)
);
CREATE TABLE `public`.`appuser` ( 
	`iduser`   	int4 NOT NULL DEFAULT nextval('appuser_iduser_seq'::regclass),
	`username` 	varchar(128) NOT NULL,
	`passwd`   	varchar(128) NOT NULL,
	`c_date`   	timestamp NULL DEFAULT now(),
	`u_date`   	timestamp NULL,
	`codhosp`  	int4 NULL,
	`country`  	varchar(16) NULL,
	`firstname`	varchar(255) NULL,
	`lastname` 	varchar(255) NULL,
	`removed`  	int4 NULL DEFAULT 0,
	`loggedin` 	int4 NULL DEFAULT 0,
	PRIMARY KEY(`iduser`)
);
CREATE TABLE `public`.`enumitem` ( 
	`idenumitem` 	int4 NOT NULL DEFAULT nextval('enumitem_idenumitem_seq'::regclass),
	`codenumtype`	int4 NOT NULL,
	`name`       	varchar(128) NULL,
	`description`	varchar(128) NULL,
	`thevalue`   	varchar(256) NULL,
	`listorder`  	int4 NULL,
	PRIMARY KEY(`idenumitem`)
);
CREATE TABLE `public`.`enumtype` ( 
	`idenumtype`	int4 NOT NULL,
	`numitems`  	int4 NULL,
	PRIMARY KEY(`idenumtype`)
);
CREATE TABLE `public`.`grouptype` ( 
	`idgrouptype`	int4 NOT NULL DEFAULT nextval('grouptype_idgrouptype_seq'::regclass),
	`name`       	varchar(128) NOT NULL,
	`description`	varchar(1024) NULL,
	PRIMARY KEY(`idgrouptype`)
);
CREATE TABLE `public`.`hospital` ( 
	`idhosp` 	int4 NOT NULL DEFAULT nextval('hospital_idhosp_seq'::regclass),
	`name`   	varchar(128) NOT NULL,
	`hospcod`	int4 NOT NULL,
	`c_date` 	timestamp NULL DEFAULT now(),
	`u_date` 	timestamp NULL,
	PRIMARY KEY(`idhosp`)
);
CREATE TABLE `public`.`interview` ( 
	`idinterview`	int4 NOT NULL DEFAULT nextval('interview_idinterview_seq'::regclass),
	`name`       	varchar(128) NULL,
	`description`	varchar(128) NULL,
	`codprj`     	int4 NULL,
	`codusr`     	int4 NULL,
	`c_date`     	timestamp NULL DEFAULT now(),
	`u_date`     	timestamp NULL,
	`source`     	int4 NULL,
	PRIMARY KEY(`idinterview`)
);
CREATE TABLE `public`.`intr_instance` ( 
	`idinstance`  	int4 NOT NULL DEFAULT nextval('intr_instance_idinstance_seq'::regclass),
	`place`       	varchar(256) NULL,
	`date_ini`    	timestamp NULL,
	`date_end`    	timestamp NULL,
	`codinterview`	int4 NOT NULL,
	PRIMARY KEY(`idinstance`)
);
CREATE TABLE `public`.`intrv_group` ( 
	`idintrv_group`	int4 NOT NULL DEFAULT nextval('intrv_group_idintrv_group_seq'::regclass),
	`codintrv`     	int4 NOT NULL,
	`codgroup`     	int4 NOT NULL,
	PRIMARY KEY(`idintrv_group`)
);
CREATE TABLE `public`.`item` ( 
	`iditem`    	int4 NOT NULL DEFAULT nextval('item_iditem_seq'::regclass),
	`idsection` 	int4 NULL,
	`ite_iditem`	int4 NULL,
	`content`   	varchar(10240) NULL,
	`item_order`	int4 NULL,
	`c_date`    	timestamp NULL DEFAULT now(),
	`u_date`    	timestamp NULL,
	`repeatable`	int4 NULL,
	`highlight` 	int4 NULL DEFAULT 0,
	PRIMARY KEY(`iditem`)
);
CREATE TABLE `public`.`pat_gives_answer2ques` ( 
	`idp_a_q`      	int4 NOT NULL DEFAULT nextval('pat_gives_answer2ques_idp_a_q_seq'::regclass),
	`codpat`       	int4 NULL,
	`codanswer`    	int4 NULL,
	`codquestion`  	int4 NULL,
	`answer_number`	int4 NULL,
	`answer_order` 	int4 NULL,
	`answer_grp`   	int4 NULL,
	PRIMARY KEY(`idp_a_q`)
);
CREATE TABLE `public`.`patient` ( 
	`idpat`     	int4 NOT NULL DEFAULT nextval('patient_idpat_seq'::regclass),
	`name`      	varchar(256) NULL,
	`codpatient`	varchar(15) NOT NULL,
	`address`   	varchar(512) NULL,
	`phone`     	varchar(20) NULL,
	`numhc`     	varchar(32) NULL,
	`c_date`    	timestamp NULL DEFAULT now(),
	`u_date`    	timestamp NULL,
	PRIMARY KEY(`idpat`)
);
CREATE TABLE `public`.`performance` ( 
	`idperformance`	int4 NOT NULL DEFAULT nextval('performance_idperformance_seq'::regclass),
	`coduser`      	int4 NULL,
	`codinterview` 	int4 NULL,
	`codpat`       	int4 NULL,
	`date_ini`     	timestamp NULL,
	`date_end`     	timestamp NULL,
	`place`        	varchar(256) NULL,
	`num_order`    	int4 NULL,
	`last_sec`     	int4 NULL DEFAULT 1,
	`codgroup`     	int4 NULL,
	PRIMARY KEY(`idperformance`)
);
CREATE TABLE `public`.`project` ( 
	`idprj`      	int4 NOT NULL DEFAULT nextval('project_idprj_seq'::regclass),
	`name`       	varchar(128) NULL,
	`description`	varchar(128) NULL,
	`c_date`     	timestamp NULL DEFAULT now(),
	`u_date`     	timestamp NULL,
	PRIMARY KEY(`idprj`)
);
CREATE TABLE `public`.`question_ansitem` ( 
	`id`          	int4 NOT NULL DEFAULT nextval('question_ansitem_id_seq'::regclass),
	`codansitem`  	int4 NOT NULL,
	`codquestion` 	int4 NOT NULL,
	`answer_order`	int4 NULL,
	`pattern`     	varchar(255) NULL,
	PRIMARY KEY(`id`)
);
CREATE TABLE `public`.`question` ( 
	`idquestion` 	int4 NOT NULL DEFAULT nextval('question_idquestion_seq'::regclass),
	`repeatable` 	int4 NULL,
	`codquestion`	varchar(16) NULL,
	`mandatory`  	int4 NULL DEFAULT 0,
	PRIMARY KEY(`idquestion`)
);
CREATE TABLE `public`.`rel_grp_appusr` ( 
	`idgrp_usr`	int4 NOT NULL DEFAULT nextval('rel_grp_appusr_idgrp_usr_seq'::regclass),
	`codgroup` 	int4 NOT NULL,
	`coduser`  	int4 NOT NULL,
	PRIMARY KEY(`idgrp_usr`)
);
CREATE TABLE `public`.`rel_prj_appusers` ( 
	`idprj_usrs`	int4 NOT NULL DEFAULT nextval('rel_prj_appusers_idprj_usrs_seq'::regclass),
	`codprj`    	int4 NOT NULL,
	`coduser`   	int4 NOT NULL,
	PRIMARY KEY(`idprj_usrs`)
);
CREATE TABLE `public`.`role` ( 
	`idrole`     	int4 NOT NULL DEFAULT nextval('role_idrole_seq'::regclass),
	`name`       	varchar(128) NULL,
	`description`	varchar(128) NULL,
	`c_date`     	timestamp NULL DEFAULT now(),
	`u_date`     	timestamp NULL,
	PRIMARY KEY(`idrole`)
);
CREATE TABLE `public`.`section` ( 
	`idsection`    	int4 NOT NULL DEFAULT nextval('section_idsection_seq'::regclass),
	`name`         	varchar(128) NULL,
	`description`  	varchar(128) NULL,
	`section_order`	int4 NULL,
	`codinterview` 	int4 NULL,
	`c_date`       	timestamp NULL DEFAULT now(),
	`u_date`       	timestamp NULL,
	PRIMARY KEY(`idsection`)
);
CREATE TABLE `public`.`text` ( 
	`idtext`     	int4 NOT NULL DEFAULT nextval('text_idtext_seq'::regclass),
	`highlighted`	int4 NULL,
	PRIMARY KEY(`idtext`)
);
CREATE TABLE `public`.`user_role` ( 
	`iduser_role`	int4 NOT NULL DEFAULT nextval('user_role_iduser_role_seq'::regclass),
	`coduser`    	int4 NOT NULL,
	`codrole`    	int4 NOT NULL,
	`username`   	varchar(128) NULL,
	`rolename`   	varchar(128) NULL,
	PRIMARY KEY(`iduser_role`)
);
CREATE TABLE `public`.`usr_pat_intrinst` ( 
	`id_upi`     	int4 NOT NULL DEFAULT nextval('usr_pat_intrinst_id_upi_seq'::regclass),
	`coduser`    	int4 NOT NULL,
	`codpatient` 	int4 NOT NULL,
	`codintr_ins`	int4 NOT NULL,
	PRIMARY KEY(`id_upi`)
);
CREATE SEQUENCE `public`.`answer_idanswer_seq`;
CREATE SEQUENCE `public`.`answer_item_idansitem_seq`;
CREATE SEQUENCE `public`.`appgroup_idgroup_seq`;
CREATE SEQUENCE `public`.`appuser_iduser_seq`;
CREATE SEQUENCE `public`.`enumitem_idenumitem_seq`;
CREATE SEQUENCE `public`.`grouptype_idgrouptype_seq`;
CREATE SEQUENCE `public`.`hospital_idhosp_seq`;
CREATE SEQUENCE `public`.`interview_idinterview_seq`;
CREATE SEQUENCE `public`.`intr_instance_idinstance_seq`;
CREATE SEQUENCE `public`.`intrv_group_idintrv_group_seq`;
CREATE SEQUENCE `public`.`item_iditem_seq`;
CREATE SEQUENCE `public`.`pat_gives_answer2ques_idp_a_q_seq`;
CREATE SEQUENCE `public`.`patient_idpat_seq`;
CREATE SEQUENCE `public`.`patient_idpatient_seq`;
CREATE SEQUENCE `public`.`performance_idperformance_seq`;
CREATE SEQUENCE `public`.`project_idprj_seq`;
CREATE SEQUENCE `public`.`project_idproject_seq`;
CREATE SEQUENCE `public`.`question_ansitem_id_seq`;
CREATE SEQUENCE `public`.`question_idquestion_seq`;
CREATE SEQUENCE `public`.`rel_grp_appusr_idgrp_usr_seq`;
CREATE SEQUENCE `public`.`rel_prj_appusers_idprj_usrs_seq`;
CREATE SEQUENCE `public`.`role_idrole_seq`;
CREATE SEQUENCE `public`.`section_idsection_seq`;
CREATE SEQUENCE `public`.`text_idtext_seq`;
CREATE SEQUENCE `public`.`user_role_iduser_role_seq`;
CREATE SEQUENCE `public`.`usr_pat_intrinst_id_upi_seq`;
CREATE SEQUENCE `public`.`applog_logId_seq`;

ALTER TABLE `public`.`answer_item`
	ADD CONSTRAINT `fked6a1af434d3ec6d`
	FOREIGN KEY(`codintrv`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`answer_item`
	ADD CONSTRAINT `fk_ansitem_intrv`
	FOREIGN KEY(`codintrv`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`answer`
	ADD CONSTRAINT `fkabca3fbe5c3d6ca1`
	FOREIGN KEY(`codansitem`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`answer`
	ADD CONSTRAINT `fk_answer_rel_answ__answer_i`
	FOREIGN KEY(`codansitem`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`answertype`
	ADD CONSTRAINT `fkb00210386a4127c5`
	FOREIGN KEY(`idanstype`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`answertype`
	ADD CONSTRAINT `fk_answerty_isoneof_answer_i`
	FOREIGN KEY(`idanstype`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`appgroup`
	ADD CONSTRAINT `fk_parent_group`
	FOREIGN KEY(`parent`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE SET DEFAULT 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`appgroup`
	ADD CONSTRAINT `fk_grouptype`
	FOREIGN KEY(`codgroup_type`)
	REFERENCES `public`.`grouptype`(`idgrouptype`)
	MATCH SIMPLE
	ON DELETE SET DEFAULT 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`appgroup`
	ADD CONSTRAINT `fk460ba8fefa6441bc`
	FOREIGN KEY(`codgroup_type`)
	REFERENCES `public`.`grouptype`(`idgrouptype`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`appgroup`
	ADD CONSTRAINT `fk460ba8fee20f1477`
	FOREIGN KEY(`parent`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`appuser`
	ADD CONSTRAINT `fkd0bc6d6cff274c45`
	FOREIGN KEY(`codhosp`)
	REFERENCES `public`.`hospital`(`idhosp`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`appuser`
	ADD CONSTRAINT `fk_hospital_user`
	FOREIGN KEY(`codhosp`)
	REFERENCES `public`.`hospital`(`idhosp`)
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE `public`.`appuser`
	ADD CONSTRAINT `fk33f5054cff274c45`
	FOREIGN KEY(`codhosp`)
	REFERENCES `public`.`hospital`(`idhosp`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`enumitem`
	ADD CONSTRAINT `fk_enumitem_contains_enumtype`
	FOREIGN KEY(`codenumtype`)
	REFERENCES `public`.`enumtype`(`idenumtype`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`enumitem`
	ADD CONSTRAINT `fk849ca7944d54c7fd`
	FOREIGN KEY(`codenumtype`)
	REFERENCES `public`.`enumtype`(`idenumtype`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`enumtype`
	ADD CONSTRAINT `fk_enumtype_isoneof2_answer_i`
	FOREIGN KEY(`idenumtype`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`enumtype`
	ADD CONSTRAINT `fk886d93fbda39f0f6`
	FOREIGN KEY(`idenumtype`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`interview`
	ADD CONSTRAINT `fk_interview_is_formed_project`
	FOREIGN KEY(`codprj`)
	REFERENCES `public`.`project`(`idprj`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`interview`
	ADD CONSTRAINT `fk_interview_belongs_user`
	FOREIGN KEY(`codusr`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE SET DEFAULT 
	ON UPDATE SET DEFAULT ;
ALTER TABLE `public`.`interview`
	ADD CONSTRAINT `fk_cloned_from`
	FOREIGN KEY(`source`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE SET DEFAULT 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`interview`
	ADD CONSTRAINT `fk1dfcd181bc927c7a`
	FOREIGN KEY(`codprj`)
	REFERENCES `public`.`project`(`idprj`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`interview`
	ADD CONSTRAINT `fk1dfcd1819fb025d9`
	FOREIGN KEY(`codusr`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`interview`
	ADD CONSTRAINT `fk1dfcd18132dc448d`
	FOREIGN KEY(`source`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`intr_instance`
	ADD CONSTRAINT `fk_instance_interview`
	FOREIGN KEY(`codinterview`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE `public`.`intrv_group`
	ADD CONSTRAINT `fk_intrvgroup_intrv`
	FOREIGN KEY(`codintrv`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`intrv_group`
	ADD CONSTRAINT `fk_intrvgroup_group`
	FOREIGN KEY(`codgroup`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`intrv_group`
	ADD CONSTRAINT `fk84c0ddb3e9d1abd4`
	FOREIGN KEY(`codgroup`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`intrv_group`
	ADD CONSTRAINT `fk84c0ddb334d3ec6d`
	FOREIGN KEY(`codintrv`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`item`
	ADD CONSTRAINT `fk_item_is_formed_section`
	FOREIGN KEY(`idsection`)
	REFERENCES `public`.`section`(`idsection`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`item`
	ADD CONSTRAINT `fk_item_contains_item`
	FOREIGN KEY(`ite_iditem`)
	REFERENCES `public`.`item`(`iditem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`item`
	ADD CONSTRAINT `fk317b13ee6627b7`
	FOREIGN KEY(`ite_iditem`)
	REFERENCES `public`.`item`(`iditem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`item`
	ADD CONSTRAINT `fk317b136ead1f80`
	FOREIGN KEY(`idsection`)
	REFERENCES `public`.`section`(`idsection`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	ADD CONSTRAINT `fkd6209a2dcefe49a3`
	FOREIGN KEY(`codanswer`)
	REFERENCES `public`.`answer`(`idanswer`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	ADD CONSTRAINT `fkd6209a2db9245433`
	FOREIGN KEY(`codquestion`)
	REFERENCES `public`.`question`(`idquestion`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	ADD CONSTRAINT `fkd6209a2d9fd61a61`
	FOREIGN KEY(`codpat`)
	REFERENCES `public`.`patient`(`idpat`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	ADD CONSTRAINT `fk_pat_give_rel_ques__question`
	FOREIGN KEY(`codquestion`)
	REFERENCES `public`.`question`(`idquestion`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	ADD CONSTRAINT `fk_pat_give_rel_pat_a_patient`
	FOREIGN KEY(`codpat`)
	REFERENCES `public`.`patient`(`idpat`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`pat_gives_answer2ques`
	ADD CONSTRAINT `fk_pat_give_rel_ans_p_answer`
	FOREIGN KEY(`codanswer`)
	REFERENCES `public`.`answer`(`idanswer`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fka7c31030e9d1abd4`
	FOREIGN KEY(`codgroup`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fka7c310309fd61a61`
	FOREIGN KEY(`codpat`)
	REFERENCES `public`.`patient`(`idpat`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fka7c310307bd5537b`
	FOREIGN KEY(`codinterview`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fka7c31030289fe600`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fk_performa_rel_pat_p_patient`
	FOREIGN KEY(`codpat`)
	REFERENCES `public`.`patient`(`idpat`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fk_performa_rel_intrv_intervie`
	FOREIGN KEY(`codinterview`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fk_performa_rel_group`
	FOREIGN KEY(`codgroup`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`performance`
	ADD CONSTRAINT `fk_performa_rel_appus_appuser`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE SET NULL 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	ADD CONSTRAINT `fk_question`
	FOREIGN KEY(`codquestion`)
	REFERENCES `public`.`question`(`idquestion`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	ADD CONSTRAINT `fk_answer_item`
	FOREIGN KEY(`codansitem`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`question_ansitem`
	ADD CONSTRAINT `fk6d9a2ea0b9245433`
	FOREIGN KEY(`codquestion`)
	REFERENCES `public`.`question`(`idquestion`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`question_ansitem`
	ADD CONSTRAINT `fk6d9a2ea05c3d6ca1`
	FOREIGN KEY(`codansitem`)
	REFERENCES `public`.`answer_item`(`idansitem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`question`
	ADD CONSTRAINT `fkba823be6e7b3fc5`
	FOREIGN KEY(`idquestion`)
	REFERENCES `public`.`item`(`iditem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`question`
	ADD CONSTRAINT `fk_question_itemisa2_item`
	FOREIGN KEY(`idquestion`)
	REFERENCES `public`.`item`(`iditem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	ADD CONSTRAINT `fk_rel_grp__rel_grp_a_appuser`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	ADD CONSTRAINT `fk_rel_grp__rel_grp_a_appgroup`
	FOREIGN KEY(`codgroup`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`rel_grp_appusr`
	ADD CONSTRAINT `fk3e240fd3e9d1abd4`
	FOREIGN KEY(`codgroup`)
	REFERENCES `public`.`appgroup`(`idgroup`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`rel_grp_appusr`
	ADD CONSTRAINT `fk3e240fd3289fe600`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`rel_prj_appusers`
	ADD CONSTRAINT `fkd0e56e24bc927c7a`
	FOREIGN KEY(`codprj`)
	REFERENCES `public`.`project`(`idprj`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`rel_prj_appusers`
	ADD CONSTRAINT `fkd0e56e24289fe600`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`rel_prj_appusers`
	ADD CONSTRAINT `fk_rel_prj__rel_prj_a_project`
	FOREIGN KEY(`codprj`)
	REFERENCES `public`.`project`(`idprj`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`rel_prj_appusers`
	ADD CONSTRAINT `fk_rel_prj__rel_prj_a_appuser`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`section`
	ADD CONSTRAINT `fk_section_is_formed_interview`
	FOREIGN KEY(`codinterview`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`section`
	ADD CONSTRAINT `fk756f7ee57bd5537b`
	FOREIGN KEY(`codinterview`)
	REFERENCES `public`.`interview`(`idinterview`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`text`
	ADD CONSTRAINT `fk_text_itemisa_item`
	FOREIGN KEY(`idtext`)
	REFERENCES `public`.`item`(`iditem`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`text`
	ADD CONSTRAINT `fk27b94df0028e8c`
	FOREIGN KEY(`idtext`)
	REFERENCES `public`.`item`(`iditem`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`user_role`
	ADD CONSTRAINT `fk_userrole_user`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`user_role`
	ADD CONSTRAINT `fk_userrole_role`
	FOREIGN KEY(`codrole`)
	REFERENCES `public`.`role`(`idrole`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`user_role`
	ADD CONSTRAINT `fk143bf46a289fe600`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`user_role`
	ADD CONSTRAINT `fk143bf46a1c3f28d3`
	FOREIGN KEY(`codrole`)
	REFERENCES `public`.`role`(`idrole`)
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION ;
ALTER TABLE `public`.`usr_pat_intrinst`
	ADD CONSTRAINT `fk_usr_ternary_rel`
	FOREIGN KEY(`coduser`)
	REFERENCES `public`.`appuser`(`iduser`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`usr_pat_intrinst`
	ADD CONSTRAINT `fk_pat_ternary_rel`
	FOREIGN KEY(`codpatient`)
	REFERENCES `public`.`patient`(`idpat`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
ALTER TABLE `public`.`usr_pat_intrinst`
	ADD CONSTRAINT `fk_intr_ins_ternary_rel`
	FOREIGN KEY(`codintr_ins`)
	REFERENCES `public`.`intr_instance`(`idinstance`)
	MATCH SIMPLE
	ON DELETE CASCADE 
	ON UPDATE CASCADE ;
